import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // IBRACORP Documentation Sidebar - Auto-generated from filesystem
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Gaming Servers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'gaming',
        },
      ],
    },
    {
      type: 'category',
      label: 'Media Servers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'media',
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        {
          type: 'autogenerated',
          dirName: 'networking',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reverse Proxies',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reverse-proxies',
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        {
          type: 'autogenerated',
          dirName: 'security',
        },
      ],
    },
    {
      type: 'category',
      label: 'Servers',
      items: [
        {
          type: 'autogenerated',
          dirName: 'servers',
        },
      ],
    },
  ],
};

export default sidebars;
